---
title: 'PT ACE2 KO 2581 Ambient RNA and Doublet Removal'
author: "Jackie Emathinger & Xiao Tong Su"
date: "2023-06-30"
output: html_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Load Packages
```{r load_new_packages, echo=T, error=FALSE, message=FALSE, warning=FALSE}
library("Seurat")
library("ggplot2")
library("tidyverse")
library("SoupX")
library("hdf5r")
library("here")
if (!require("DoubletFinder")) {BiocManager::install('DoubletFinder'); require("DoubletFinder")}

here()
#if (!require("remotes")) {install.packages("remotes"); require("remotes")}

#remotes::install_github('chris-mcginnis-ucsf/DoubletFinder')
library("DoubletFinder")
#install.packages("hdf5r")


```

# SoupX for Ambient RNA Removal
[(Young and Behjati, 2020)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7763177/)
```{r pre_process, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.align = 'center'}
tod = Read10X_h5(here("Cell Ranger Files", "8_raw_feature_bc_matrix.h5")) #Change
toc = Read10X_h5(here("Cell Ranger Files", "8_filtered_feature_bc_matrix.h5")) #Change 
sc = SoupChannel(tod,toc)

#Make the Seurat object from the filtered control data
SO <- Read10X_h5(here("Cell Ranger Files", "8_filtered_feature_bc_matrix.h5")) #Change 
SO <- CreateSeuratObject(counts = SO, project = "PT ACE2 KO")  #Change

#Cluster the cells with Seurat
SO <- SCTransform(SO, verbose = F)
SO <- RunPCA(SO, verbose = F)
SO <- RunUMAP(SO, dims = 1:30, verbose = F)
SO <- FindNeighbors(SO, dims = 1:30, verbose = F)
SO <- FindClusters(SO, verbose = T)
 
meta <- SO@meta.data
umap <- SO@reductions$umap@cell.embeddings
clusters <- setNames(meta$seurat_clusters, rownames(meta))

#Sanity Check
length(clusters) #should be equal to nrow(sc$metaData)
nrow(sc$metaData)

sc <- setClusters(sc, clusters)
sc <- setDR(sc, umap)

#Estimate rho
sc = autoEstCont(sc)

#Clean the data
SO_out = adjustCounts(sc)
 
#Create a new Seurat Object out of the cleaned data
seurat.obj <- CreateSeuratObject(SO_out)
```

# Pre-process for Doublet Finder
[(McGinnis et al., 2019)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6853612/)
```{r pre_process2, echo=TRUE, error=FALSE, fig.align= 'center', message=FALSE, warning=FALSE}

VlnPlot(seurat.obj, features = c("nFeature_RNA", "nCount_RNA"), ncol = 2)

# Minimal QC and Filtering (low quality cells) to let doublet find doublets

seurat.obj.f <- subset(seurat.obj, nFeature_RNA > 500 & nCount_RNA < 20000)

VlnPlot(seurat.obj.f, features = c("nFeature_RNA", "nCount_RNA"), ncol = 2)

seurat.obj.f

# Pre-process standard workflow
seurat.obj.f <- NormalizeData(object = seurat.obj.f)
seurat.obj.f <- FindVariableFeatures(object = seurat.obj.f)
seurat.obj.f <- ScaleData(object = seurat.obj.f)
seurat.obj.f <- RunPCA(object = seurat.obj.f)
ElbowPlot(seurat.obj.f, ndims = 40)

# Determine percent of variation associated with each PC
pct <- seurat.obj.f[["pca"]]@stdev / sum(seurat.obj.f[["pca"]]@stdev) * 100

# Calculate cumulative percents for each PC
cumu <- cumsum(pct)

# Determine which PC exhibits cumulative percent greater than 90% and % variation associated with the PC as less than 5
co1 <- which(cumu > 90 & pct < 5)[1]

co1

# Determine the difference between variation of PC and subsequent PC
co2 <- sort(which((pct[1:length(pct) - 1] - pct[2:length(pct)]) > 0.1), decreasing = T)[1] + 1

# last point where change of % of variation is more than 0.1%.
co2
# Minimum of the two calculation
pcs <- min(co1, co2)

pcs

# Create a dataframe with values
plot_df <- data.frame(pct = pct, 
           cumu = cumu, 
           rank = 1:length(pct))

# Elbow plot to visualize 
  ggplot(plot_df, aes(cumu, pct, label = rank, color = rank > pcs)) + 
  geom_text() + 
  geom_vline(xintercept = 90, color = "grey") + 
  geom_hline(yintercept = min(pct[pct > 5]), color = "grey") +
  theme_bw()
  
#Dimensionality heatmaps: These are plots of PCA weightings for the most highly and lowly weighted genes, shown against the set of cells which are most highly influenced by the PC. The idea is that as long as we’re seeing clear structure in one of these plots then we’re still adding potentially useful information to the analysis.
DimHeatmap(seurat.obj.f,dims=1:pcs, cells=500)

# Based on the pcs calculated above, use 21
seurat.obj.f <- FindNeighbors(object = seurat.obj.f, dims = 1:pcs)
seurat.obj.f <- FindClusters(object = seurat.obj.f, resolution = 0.03)
seurat.obj.f <- RunUMAP(object = seurat.obj.f, dims = 1:pcs)
DimPlot(seurat.obj.f, reduction = "umap")

```

```{r find_parameters_1, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.align = 'center', results=F}

# Calculate each combination of pN and pK
sweep.res.list_seurat.obj.f <- paramSweep_v3(seurat.obj.f, PCs = 1:pcs, sct = FALSE) 
```

```{r find_parameters_2, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.align = 'center'}

#Summarize each combination of pN and pK
sweep.stats_seurat.obj.f <- summarizeSweep(sweep.res.list_seurat.obj.f, GT = FALSE) 

#Select the pK that corresponds to max bcmvn to optimize doublet detection
bcmvn_seurat.obj.f <- find.pK(sweep.stats_seurat.obj.f)
pK <- bcmvn_seurat.obj.f %>% 
  filter(BCmetric == max(BCmetric)) %>%
  select(pK) 

#See pK in the Values Environment
pK <- as.numeric(as.character(pK[[1]]))

```


```{r homotypic_doublets, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.align = 'center'}

# Homotypic Doublet Proportion Estimate -------------------------------------------------------------------------------------
annotations <- seurat.obj.f@meta.data$seurat_clusters  

homotypic.prop <- modelHomotypic(annotations)           
homotypic.prop

ncol(x=seurat.obj.f)

nExp_poi <- (0.072*nrow(seurat.obj.f@meta.data)) #Change
nExp_poi
nExp_poi_adj <- round(nExp_poi*(1-homotypic.prop))

```

# Doublet Finder
```{r doublet_finder, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.align = 'center'}

seurat.obj.f_doublets <- doubletFinder_v3(seurat.obj.f,
                        PCs = 1:pcs,
                        pN = 0.25,
                        pK = pK,
                        nExp = nExp_poi_adj,
                        reuse.pANN = FALSE, sct = FALSE)
colnames(seurat.obj.f_doublets@meta.data)[6] <- "pANN"
colnames(seurat.obj.f_doublets@meta.data)[7] <- "DF.class"
head(seurat.obj.f_doublets@meta.data)
table(seurat.obj.f_doublets@meta.data$DF.class)

DimPlot(seurat.obj.f_doublets, group.by = "DF.class")

VlnPlot(seurat.obj.f_doublets, "nFeature_RNA", group.by = "DF.class")

VlnPlot(seurat.obj.f_doublets, "nCount_RNA", group.by = "DF.class")

```


# Subset singlets
```{r subset, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.align = 'center'}

seurat.obj.f_singlets <- subset(seurat.obj.f_doublets, DF.class == "Singlet")
seurat.obj.f_singlets
DimPlot(seurat.obj.f_singlets, reduction = "umap")
```

# Add Meta data
```{r meta data, echo=TRUE, error=FALSE, fig.align= 'center', message=FALSE, warning=FALSE}

#Sample	Mouse ID	Genotype	Treatment	Enrichment	Cohort	Sample Processor
#1	2584	Cre -	Saline	n/a	1	JWN
#2	2580	Cre +	AngII	n/a	1	JWN
#3	2583	Cre +	Saline	n/a	1	JME
#4	2743	Cre -	AngII	n/a	1	JME
#5	2582	Cre +	Saline	n/a	2	JWN
#6	2701	Cre -	AngII	n/a	2	JWN
#7	2744	Cre -	Saline	n/a	2	JME
#8	2581	Cre +	AngII	n/a	2	JME


seurat.obj.f_singlets[["percent.mt"]] <- PercentageFeatureSet(seurat.obj.f_singlets, pattern = "^mt-")

seurat.obj.f_singlets <- AddMetaData(object = seurat.obj.f_singlets, metadata = "2581", col.name = "Sample_ID") #Change
seurat.obj.f_singlets <- AddMetaData(object = seurat.obj.f_singlets, metadata = "Cre +", col.name = "Genotype") #Change
seurat.obj.f_singlets <- AddMetaData(object = seurat.obj.f_singlets, metadata = "AngII", col.name = "Treatment") #Change
seurat.obj.f_singlets <- AddMetaData(object = seurat.obj.f_singlets, metadata = "n/a", col.name = "Enrichment") #Change
seurat.obj.f_singlets <- AddMetaData(object = seurat.obj.f_singlets, metadata = "Second", col.name = "Cohort") #Change
seurat.obj.f_singlets <- AddMetaData(object = seurat.obj.f_singlets, metadata = "JME", col.name = "Sample_Processor") #Change

head(seurat.obj.f_singlets@meta.data)

```

# Remove Mitochondrial Genes
```{r mito, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.align = 'center'}

seurat.obj.f_singlets <- seurat.obj.f_singlets[!grepl("^mt-", rownames(seurat.obj.f_singlets)), ]

#Mito Sanity Check
counts <- GetAssayData(seurat.obj.f_singlets, assay = "RNA")
mito.genes <- grep(pattern = "^mt-", x = rownames(x = counts), value = TRUE) 
mito.genes #should be zero

DimPlot(seurat.obj.f_singlets, reduction = "umap", label = T)
```

# Initial Cluster Identification
```{r cluster, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.align = 'center', fig.width = 7, fig.height= 8}

seurat.obj.f_singlets.markers <- FindAllMarkers(seurat.obj.f_singlets, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)

seurat.obj.f_singlets.markers %>%
    group_by(cluster) %>%
    top_n(n = 5, wt = avg_log2FC) -> top5

DoHeatmap(seurat.obj.f_singlets, features = top5$gene) + NoLegend()

seurat.obj.f_singlets.markers %>%
    group_by(cluster) %>%
    top_n(n = 2, wt = avg_log2FC) -> top2

VlnPlot(seurat.obj.f_singlets, 
        features = unique(top2$gene),
        stack = TRUE, 
        flip = TRUE,
        pt.size = 0)+
        NoLegend()

```


```{r dotplot, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.align = 'center'}

DotPlot(seurat.obj.f_singlets, features = unique(top2$gene), dot.scale = 8, cols = c("dodgerblue2", "coral2")) + RotatedAxis()
 
```


# Output Files
```{r pdf, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.align = 'center'}

saveRDS(seurat.obj.f_singlets, here("Temp Outputs", "2581.rds")) #Change

```

# Session Info
```{r sessioninfo, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE, fig.align = 'center'}

sessionInfo()

```